### ISSUE TITLE
CASCADE deletion of model with nested polymorphic models fail with xxx_ptr does not exist error

### ISSUE THREAD

**Issue by DanSheps** [jazzband/django-polymorphic#608]
I have the following mdels:

```

class PolyDevice(Model):
    name = CharField(max_length=64)

class NotPolyInterface(PolymorphicModel):
    name = CharField(max_length=64)
    device = ForeignKey(to=PolyDevice, on_delete=CASCADE)
    ethernety_stuff = CharField(max_length=64)
    modular_stuff = CharField(max_length=64)
    fixed_stuff = CharField(max_length=64)
    wirelessy_stuff = CharField(max_length=64)
    fc_stuff = CharField(max_length=64)

class PolyInterface(PolymorphicModel):
    name = CharField(max_length=64)
    device = ForeignKey(to=PolyDevice, on_delete=CASCADE)

class PolyEthernetInterface(PolyInterface):
    ethernety_stuff = CharField(max_length=64)

class PolyModularInterface(PolyEthernetInterface):
    modular_stuff = CharField(max_length=64)

class PolyFixedInterface(PolyEthernetInterface):
    fixed_stuff = CharField(max_length=64)

class PolyWirelessInterface(PolyInterface):
    wirelessy_stuff = CharField(max_length=64)

class PolyFCInterface(PolyInterface):
    fc_stuff = CharField(max_length=64)
```

When I initialize a device and then initialize one of each type of interface (Fixed, Modular, Wireless, FC) and then attempt to delete the device, I receive the following error:

```
>>> PolyDevice.objects.first().delete()
Traceback (most recent call last):
  File "C:\Users\dan\AppData\Local\Programs\Python\Python310\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "C:\Development\test\venv\lib\site-packages\django\db\models\base.py", line 1131, in delete
    collector.collect([self], keep_parents=keep_parents)
  File "C:\Development\test\venv\lib\site-packages\django\db\models\deletion.py", line 350, in collect
    on_delete(self, field, sub_objs, self.using)
  File "C:\Development\test\venv\lib\site-packages\django\db\models\deletion.py", line 23, in CASCADE
    collector.collect(
  File "C:\Development\test\venv\lib\site-packages\django\db\models\deletion.py", line 298, in collect
    parent_objs = [getattr(obj, ptr.name) for obj in new_objs]
  File "C:\Development\test\venv\lib\site-packages\django\db\models\deletion.py", line 298, in <listcomp>
    parent_objs = [getattr(obj, ptr.name) for obj in new_objs]
AttributeError: 'PolyWirelessInterface' object has no attribute 'polyethernetinterface_ptr'. Did you mean: 'polyethernetinterface'?
```

**Comment by leolivier** [comment]
I have not exactly the same issue as I get another exception:
My model is (simplified extract)
```python
class Poll(Model):
   ...
   pass

class Question(Model):
   poll = ForeignKey((to=Poll, on_delete=CASCADE)
   ...

class Answer(PolymorphicModel):
   question = ForeignKey((to=Question, on_delete=CASCADE)
   ...

class TextAnswer(Answer):
   answer = CharField(default="", blank=True, max_length=500)
   ...

class YesNoAnswer(Answer):
   answer = models.BooleanField(_('answer'), default=False)
   ...
```
and other kind of answers...
When I do:
```python
poll = Poll()
question = Question(poll=poll)
answer1 = TextAnswer(question=question, answer="test")
answer2 = YesNoAnswer(question=question, answer=True)

poll.delete()
```
I get the Poll, the Question and the Answer instances deleted but at the end of test, the instances of TextAnswer and YesNoAnswer remain and I get :
```
django.db.utils.IntegrityError: The row in table 'polls_textanswer' with primary key '3' has an invalid foreign key: polls_textanswer.answer_ptr_id contains a value '3' that does not have a corresponding value in polls_answer.id.
```
and if I trace:
```
Answer.objects.count() ==> 0
TextAnswer.objects.count() ==> 1
YesNoAnswer.objects.count() ==> 1
```
and even weirder:
```
TextAnswer.objects.all() ==> <PolymorphicQuerySet []>
```
although the count is 1!

I noticed that the CASCADE standard function calls a collect method which is waiting for a "homogeneous iterable collection of
model instances (e.g. a QuerySet)" (see django.db.models.deletion.py : 244) 
But when I debug it, the PolymorphicSet contains different subclasses instances so not really homogeneous and the code of this method is doing `model = new_objs[0].__class__`  (see line 287) and afterwards works with this model as if it was the model of all the objects which obviously can't work in our case...

**Comment by lode-braced** [comment]
I had this issue too: foreign keys defined in a parent polymorphic model would only cascade into _one_ of the child models. The issue does indeed lie with that collect expecting a homogeneous collection, which a polymorphic queryset is not. I fixed this by making a slightly modified cascade function: 
```python
from django.db.models.deletion import CASCADE
from polymorphic.query import PolymorphicQuerySet

def POLYMORPHIC_CASCADE(collector, field, sub_objs, using):
    if isinstance(sub_objs, PolymorphicQuerySet):
        sub_objs = sub_objs.non_polymorphic()
    return CASCADE(collector, field, sub_objs, using)
```

This ensures that that cascade collector _is_ passed a homogeneous queryset, one containing instances of the parent model. Child instances still delete, as they are themselves collected through their foreign keys to the parent model.

@leolivier in your example this should mean changing `poll = ForeignKey((to=Poll, on_delete=CASCADE)` to `poll = ForeignKey(to=Poll, on_delete=POLYMORPHIC_CASCADE)`.

**Comment by lode-braced** [comment]
@bckohan not sure if the above is worth making into a PR?

I'm willing to do so if it's worth being included into the package. I'm not sure on what's the most graceful implementation of this  as a part of the package. Some of the options I see:

1. In an init of a polymorphic model, override field definitions using `CASCADE` to use `POLYMORPHIC_CASCADE`
2.  Make users explicitly use the polymorphic cascade, with e.g., a system check warning when a polymorphic class with children uses cascade instead of the polymorphic cascade.

Tradeoff between the two being refactor work for the polymorphic users (option 2) vs "magic", hidden functionality that may cause unexpected side effects (option 1).
